---

galaxy_info:
  role_name: silence
  namespace: bodsch

  author: Bodo Schulz
  description: ansible role to handle silence modes in alertmanager
  license: Apache
  min_ansible_version: "2.10"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 10
        - buster
        # 11
        - bullseye
    - name: Ubuntu
      versions:
        # 20.04
        - focal

  galaxy_tags:
    - prometheus
    - alertmanager
    - monitoring

dependencies: []

...
