---

- name: user and group handling
  when:
    - not running_in_check_mode
    - docker_sd_system_user != "root" or docker_sd_system_group != "root"
  block:
    - name: create docker-sd group
      ansible.builtin.group:
        name: "{{ docker_sd_system_group }}"
        state: present
        system: true
      when:
        - docker_sd_system_group != "root"

    - name: create docker-sd user
      ansible.builtin.user:
        name: "{{ docker_sd_system_user }}"
        groups: "{{ docker_sd_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent
      when:
        - docker_sd_system_user != "root"

- name: create install directory
  when:
    - not running_in_check_mode
  ansible.builtin.file:
    path: "{{ docker_sd_install_path }}"
    state: directory
    owner: "{{ docker_sd_system_user }}"
    group: "{{ docker_sd_system_group }}"
    mode: "0755"

- name: deploy and activate docker_sd version {{ docker_sd_version }}
  when:
    - not running_in_check_mode
  bodsch.core.deploy_and_activate:
    src_dir: "{{ docker_sd_local_tmp_directory }}"
    install_dir: "{{ docker_sd_install_path }}"
    link_dir: "/usr/bin"
    remote_src: "{{ ('true' if docker_sd_direct_download else 'false') | bool }}"
    owner: "{{ docker_sd_system_user }}"
    group: "{{ docker_sd_system_group }}"
    mode: "0755"
    items:
      - name: "{{ docker_sd_release.binary }}"
        capability: "cap_net_raw+ep"
  notify:
    - restart docker-sd

- name: create docker_sd configuration directory
  when:
    - not running_in_check_mode
  ansible.builtin.file:
    path: "{{ docker_sd_config_dir }}"
    state: directory
    owner: root
    group: "{{ docker_sd_system_group }}"
    mode: "0770"

- name: systemd
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
  block:
    - name: create docker-sd system configuration
      ansible.builtin.template:
        src: "default/docker-sd.j2"
        dest: "{{ docker_sd_defaults_directory }}/docker-sd"
        force: true
        owner: root
        group: "{{ docker_sd_system_group }}"
        mode: "0640"
      notify:
        - restart docker-sd

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/docker-sd.service.j2"
        dest: "{{ systemd_lib_directory }}/docker-sd.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - daemon-reload

- name: openrc
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/docker-sd.j2"
        dest: "/etc/conf.d/docker-sd"
        owner: root
        group: root
        mode: "0644"

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/docker-sd.j2"
        dest: "/etc/init.d/docker-sd"
        owner: root
        group: root
        mode: "0750"

- name: create custom fact file
  when:
    - not running_in_check_mode
  bodsch.core.facts:
    name: docker_sd
    facts:
      version: "{{ docker_sd_version }}"

...
