---

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  notify: restart blackbox_exporter
  when:
    - ansible_service_mgr == 'systemd'

- name: validate config  # noqa no-handler
  become: true
  ansible.builtin.command: |
    /usr/bin/blackbox_exporter \
      --config.file {{ blackbox_exporter_service.config.file }} \
      --config.check
  register: _validate
  changed_when: _validate.rc != 0
  failed_when: _validate.rc != 0

- name: restart blackbox exporter
  become: true
  ansible.builtin.service:
    name: blackbox_exporter
    state: restarted

- name: reload blackbox exporter
  become: true
  ansible.builtin.service:
    name: blackbox_exporter
    state: reloaded

...
