---

galaxy_info:
  role_name: nginx_exporter
  namespace: bodsch

  author: Bodo Schulz

  description: install Nginx prometheus exporter

  license: Apache

  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 10
        - buster
        # 11
        - bullseye
    - name: Ubuntu
      versions:
        # 20.04
        - focal

  galaxy_tags:
    - monitoring
    - prometheus
    - metrics
    - exporter
    - nginx

dependencies: []
