---

prometheus_service:
  log:
    level: debug
  web:
    listen_address: "0.0.0.0:9090"

prometheus_global:
  scrape_interval: 5m
  evaluation_interval: 2m
  external_labels:
    environment: MOLECULE
    production: not

prometheus_alerting:
  alert_relabel_configs: []
  alertmanagers: []

prometheus_file_sd_targets:
  #
  node:
    - targets:
        - localhost:9100
      labels:
        env: test

  kresd:
    - labels:
        service: dns
      targets:
        - ns.matrix.lan:8453

prometheus_scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9090"
  #
  - job_name: kresd
    file_sd_configs:
      - files:
          - "{{ prometheus_config_dir }}/file_sd/kresd.yml"

prometheus_remote_write:
  - url: http://10.18.0.2:9190/api/v1/write
    basic_auth:
      username: 'your-username'
      password: 'your-password'
    queue_config:
      capacity: 5000
      max_shards: 10
      max_samples_per_send: 1000
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 100ms

...
