---

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

- name: restart mongodb exporter
  become: true
  ansible.builtin.service:
    name: mongodb_exporter
    state: restarted

- name: reload mongodb exporter
  become: true
  ansible.builtin.service:
    name: mongodb_exporter
    state: reloaded

...
