---

nginx_vhosts:

  - name: default
    description: |
      simply a default vhost
    ssl:
      enabled: false

  - name: nginx-status
    filename: 00-status.conf
    state: present  # default: present
    enabled: true   # default: true
    # domain(s)
    domains:
      - localhost
    # listen
    listen:
      - 127.0.0.1:8088

    # locations
    locations:
      "/nginx_status":
        options: |
          stub_status on;
          access_log off;
          allow 127.0.0.1;
          deny all;
...
