---

- name: create install directory
  when:
    - not running_in_check_mode
  ansible.builtin.file:
    path: "{{ promcheck_install_path }}"
    state: directory
    mode: "0755"

- name: deploy and activate promcheck version {{ promcheck_version }}
  when:
    - not running_in_check_mode
  bodsch.core.deploy_and_activate:
    src_dir: "{{ promcheck_local_tmp_directory }}"
    install_dir: "{{ promcheck_install_path }}"
    link_dir: "/usr/bin"
    remote_src: "{{ ('true' if promcheck_direct_download else 'false') | bool }}"
    mode: "0755"
    items:
      - name: "{{ promcheck_release.binary }}"

- name: create custom fact file
  when:
    - not running_in_check_mode
  bodsch.core.facts:
    name: promcheck
    facts:
      version: "{{ promcheck_version }}"

...
