---

- name:
  tags:
    - silence_add
  block:
    - name: define date time
      ansible.builtin.set_fact:
        date_time: "{{ '' | bodsch.prometheus.current_datetime(silence_downtime) }}"
        # silence_start_datetime: "{{ '' | bodsch.prometheus.local_time_iso8601 }}"
        # silence_end_datetime: "{{ '' | bodsch.prometheus.local_time_iso8601 | bodsch.prometheus.add_time_iso8601(minutes=silence_downtime.minutes)  }}"

    - name: define start and end time
      ansible.builtin.set_fact:
        silence_start_datetime: "{{ date_time.begin }}"
        silence_end_datetime: "{{ date_time.end  }}"

    - name: silence will end
      ansible.builtin.debug:
        msg:
          - "alertmanager silence will start: {{ silence_start_datetime }}"
          - "alertmanager silence will end  : {{ silence_end_datetime }}"

    - name: silence alertmanager for deployment
      ansible.builtin.uri:
        url: "{{ silence_alertmanager.url }}/api/v2/silences"
        method: POST
        body_format: json
        body: >
          {
            "matchers": [
              {
                "name": "environment",
                "value": "{{ silence_environment.name }}",
                "isRegex": false
              }
            ],
            "startsAt": "{{ silence_start_datetime }}",
            "endsAt": "{{ silence_end_datetime }}",
            "createdBy": "automation",
            "comment": "Silence for ansible-deployment",
            "status": {
              "state": "active"
            }
          }
      register: silence_resp

    - name: result
      ansible.builtin.debug:
        msg: "{{ silence_resp.json.status }}"

    - name: define silence_id
      ansible.builtin.set_fact:
        silence_silence_id: "{{ silence_resp.json.data.silenceId }}"

    - name: save silencer fact
      bodsch.core.facts:
        name: silence
        facts:
          silence_id: "{{ silence_silence_id }}"
          start_datetime: "{{ silence_start_datetime }}"
          end_datetime: "{{ silence_end_datetime }}"
      when:
        - silence_silence_id is defined

    # - name: save silencer fact
    #   block:
    #     - name: create custom fact file
    #       template:
    #         src: facts.d/alertmanager_silencer.facts.j2
    #         dest: /etc/ansible/facts.d/alertmanager_silencer.fact
    #         owner: root
    #         group: root
    #         mode: 0o755
    #
    #     - name: do facts module to get latest information
    #       setup:
    #   when:
    #     - silence_silence_id is defined



...
