---

pushgateway_main_version: "{{ pushgateway_version[0:3] }}"

pushgateway_install_path: /usr/local/opt/pushgateway/{{ pushgateway_version }}

pushgateway_delegate_to: localhost

pushgateway_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/pushgateway', true) }}/{{ pushgateway_version }}"

pushgateway_requirements:
  - iproute2

pushgateway_defaults_service:
  log:
    level: info
    format: ""
  web:
    config:
      file: ""
    listen_address: "127.0.0.1:9091"
    telemetry_path: ""
    external_url: ""
    route_prefix: ""
    enable_lifecycle: false
    enable_admin_api: false
  persistence:
    file: ""
    interval: 5m
  push:
    disable_consistency_check: false

pushgateway_defaults_directory: /etc/default

pushgateway_defaults_release:
  download_url: https://github.com/prometheus/pushgateway/releases/
  file: pushgateway-{{ pushgateway_version }}.{{ ansible_system | lower }}-{{ system_architecture }}.tar.gz

go_arch_map:
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'
  armv6l: 'armv6'

system_architecture: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

systemd_lib_directory: /lib/systemd/system

...
