---

node_exporter_main_version: "{{ node_exporter_version[0:3] }}"

node_exporter_install_path: /usr/local/opt/node_exporter/{{ node_exporter_version }}

node_exporter_delegate_to: localhost

node_exporter_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/node_exporter', true) }}/{{ node_exporter_version }}"

node_exporter_requirements:
  - iproute2
  - gzip

node_exporter_defaults_service:
  log:
    level: info
    format: ""
  path:
    procfs: /proc         # procfs mountpoint.
    sysfs: /sys           # sysfs mountpoint.
    root: /               # rootfs mountpoint.
  web:
    # [EXPERIMENTAL]
    # Path to configuration file that can enable TLS or authentication.
    config:
      file: ""
    # Address on which to expose metrics and web interface.
    listen_address: "0.0.0.0:9100"
    # Path under which to expose metrics.
    telemetry_path: "/metrics"
    # Exclude metrics about the exporter itself (promhttp_*, process_*, go_*).
    disable_exporter_metrics: false
    # Maximum number of parallel scrape requests. Use 0 to disable.
    max_requests: 40

node_exporter_defaults_tls_server: {}

node_exporter_defaults_http_server: {}

node_exporter_defaults_basic_auth_users: {}

node_exporter_defaults_rules: {}

node_exporter_defaults_collectors:
  enabled: []
  disabled: []

node_exporter_defaults_directory: /etc/default

node_exporter_defaults_release:
  download_url: https://github.com/prometheus/node_exporter/releases
  file: node_exporter-{{ node_exporter_version }}.{{ ansible_system | lower }}-{{ system_architecture }}.tar.gz
  binary: node_exporter

# ---------------------------------------------

go_arch_map:
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'armv7'

system_architecture: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

systemd_lib_directory: /lib/systemd/system


...
