---

- name: user and group handling
  when:
    - ssl_exporter_system_user != "root"
  block:
    - name: create ssl_exporter group
      ansible.builtin.group:
        name: "{{ ssl_exporter_system_group }}"
        state: present
        system: true

    - name: create ssl_exporter user
      ansible.builtin.user:
        name: "{{ ssl_exporter_system_user }}"
        groups: "{{ ssl_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ ssl_exporter_install_path }}"
    state: directory
    owner: "{{ ssl_exporter_system_user }}"
    group: "{{ ssl_exporter_system_group }}"
    mode: 0755

- name: detect extracted binary file for ssl_exporter on '{{ ssl_exporter_delegate_to }}'
  become: false
  delegate_to: "{{ ssl_exporter_delegate_to }}"
  run_once: "{{ 'false' if ssl_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ ssl_exporter_local_tmp_directory }}/{{ ssl_exporter_release.binary }}"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: detect installed ssl_exporter binary
  ansible.builtin.stat:
    path: "{{ ssl_exporter_install_path }}/{{ ssl_exporter_release.binary }}"
  register: stat_ssl_exporter_binary

- name: detect activated ssl_exporter binary
  ansible.builtin.stat:
    path: /usr/bin/{{ ssl_exporter_release.binary }}
  register: stat_ssl_exporter_activated

- name: install and activate ssl_exporter
  when:
    - (stat_ssl_exporter_binary.stat is defined and not stat_ssl_exporter_binary.stat.exists | default('false')) or
      not stat_ssl_exporter_activated.stat | bodsch.prometheus.linked_version(ssl_exporter_install_path, ssl_exporter_version)
  block:
    - name: propagate files
      block:
        - name: propagate ssl_exporter binary
          ansible.builtin.copy:
            src: "{{ ssl_exporter_local_tmp_directory }}/{{ ssl_exporter_release.binary }}"
            dest: "{{ ssl_exporter_install_path }}/{{ ssl_exporter_release.binary }}"
            mode: 0755
            owner: "{{ ssl_exporter_system_user }}"
            group: "{{ ssl_exporter_system_group }}"
            remote_src: "{{ 'true' if ssl_exporter_direct_download else 'false' }}"

        - name: make files executable
          ansible.builtin.file:
            path: "{{ ssl_exporter_install_path }}/{{ ssl_exporter_release.binary }}"
            mode: 0755
            owner: "{{ ssl_exporter_system_user }}"
            group: "{{ ssl_exporter_system_group }}"

        - name: ensure ssl exporter binary has cap_net_raw capability
          capabilities:
            path: "{{ ssl_exporter_install_path }}/{{ ssl_exporter_release.binary }}"
            capability: cap_net_raw+ep
            state: present
          when:
            - not ansible_check_mode

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ ssl_exporter_install_path }}/{{ ssl_exporter_release.binary }}"
            dest: /usr/bin/{{ ssl_exporter_release.binary }}
            state: link
            force: true
            follow: false
          notify:
            - restart ssl exporter

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ ssl_exporter_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create ssl_exporter run configuration
      ansible.builtin.template:
        src: "default/ssl_exporter.j2"
        dest: "{{ ssl_exporter_defaults_directory }}/ssl_exporter"
        force: true
        owner: root
        group: "{{ ssl_exporter_system_group }}"
        mode: 0640
      notify:
        - restart ssl exporter

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/ssl_exporter.service.j2"
        dest: "{{ systemd_lib_directory }}/ssl_exporter.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart ssl exporter

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/ssl_exporter.j2"
        dest: "/etc/conf.d/ssl_exporter"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/ssl_exporter.j2"
        dest: "/etc/init.d/ssl_exporter"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  bodsch.core.facts:
    name: ssl_exporter
    facts:
      version: "{{ ssl_exporter_version }}"

...
