---

- name: user and group handling
  when:
    - blackbox_exporter_system_user != "root"
  block:
    - name: create blackbox_exporter group
      ansible.builtin.group:
        name: "{{ blackbox_exporter_system_group }}"
        state: present
        system: true

    - name: create blackbox_exporter user
      ansible.builtin.user:
        name: "{{ blackbox_exporter_system_user }}"
        groups: "{{ blackbox_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ blackbox_exporter_install_path }}"
    state: directory
    owner: "{{ blackbox_exporter_system_user }}"
    group: "{{ blackbox_exporter_system_group }}"
    mode: 0755

- name: detect extracted binary file for blackbox_exporter on '{{ blackbox_exporter_delegate_to }}'
  become: false
  delegate_to: "{{ blackbox_exporter_delegate_to }}"
  run_once: "{{ 'false' if blackbox_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ blackbox_exporter_local_tmp_directory }}/{{ blackbox_exporter_release.binary }}"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: detect installed blackbox_exporter binary
  ansible.builtin.stat:
    path: "{{ blackbox_exporter_install_path }}/{{ blackbox_exporter_release.binary }}"
  register: stat_blackbox_exporter_binary

- name: detect activated blackbox_exporter binary
  ansible.builtin.stat:
    path: /usr/bin/{{ blackbox_exporter_release.binary }}
  register: stat_blackbox_exporter_activated

- name: install and activate blackbox_exporter
  when:
    - stat_blackbox_exporter_binary.stat is defined
    - not stat_blackbox_exporter_binary.stat.exists | default('false')
    - stat_blackbox_exporter_activated.stat is defined
    - not stat_blackbox_exporter_activated.stat.exists | default('false')
  block:
    - name: propagate files
      block:
        - name: propagate blackbox_exporter binary
          ansible.builtin.copy:
            src: "{{ blackbox_exporter_local_tmp_directory }}/{{ blackbox_exporter_release.binary }}"
            dest: "{{ blackbox_exporter_install_path }}/{{ blackbox_exporter_release.binary }}"
            mode: 0755
            owner: "{{ blackbox_exporter_system_user }}"
            group: "{{ blackbox_exporter_system_group }}"
            remote_src: "{{ 'true' if blackbox_exporter_direct_download else 'false' }}"

        - name: make files executable
          ansible.builtin.file:
            path: "{{ blackbox_exporter_install_path }}/{{ blackbox_exporter_release.binary }}"
            mode: 0755
            owner: "{{ blackbox_exporter_system_user }}"
            group: "{{ blackbox_exporter_system_group }}"

        - name: ensure blackbox exporter binary has cap_net_raw capability
          capabilities:
            path: "{{ blackbox_exporter_install_path }}/{{ blackbox_exporter_release.binary }}"
            capability: cap_net_raw+ep
            state: present
          when:
            - not ansible_check_mode

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ blackbox_exporter_install_path }}/{{ blackbox_exporter_release.binary }}"
            dest: /usr/bin/{{ blackbox_exporter_release.binary }}
            state: link
            force: true
            follow: false
          notify:
            - restart blackbox exporter

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ blackbox_exporter_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create blackbox_exporter run configuration
      ansible.builtin.template:
        src: "default/blackbox_exporter.j2"
        dest: "{{ blackbox_exporter_defaults_directory }}/blackbox_exporter"
        force: true
        owner: root
        group: "{{ blackbox_exporter_system_group }}"
        mode: 0640
      notify:
        - restart blackbox exporter

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/blackbox_exporter.service.j2"
        dest: "{{ systemd_lib_directory }}/blackbox_exporter.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart blackbox exporter

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/blackbox_exporter.j2"
        dest: "/etc/conf.d/blackbox_exporter"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/blackbox_exporter.j2"
        dest: "/etc/init.d/blackbox_exporter"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  bodsch.core.facts:
    name: blackbox_exporter
    facts:
      version: "{{ blackbox_exporter_version }}"

...
