---

- name: prepare
  ansible.builtin.import_tasks: prepare.yml
  tags:
    - blackbox_exporter_install
    - blackbox_exporter_configure
    - blackbox_exporter_run

- name: download archive
  ansible.builtin.import_tasks: download.yml
  become: true
  when:
    - not stat_blackbox_exporter_binary.stat.exists or
      not stat_blackbox_exporter_binary.stat.path == blackbox_exporter_install_path ~ '/blackbox_exporter'
  tags:
    - blackbox_exporter_install

- name: install
  ansible.builtin.import_tasks: install.yml
  when:
    - not stat_blackbox_exporter_binary.stat.exists or
      not stat_blackbox_exporter_binary.stat.path == blackbox_exporter_install_path ~ '/blackbox_exporter'
  tags:
    - blackbox_exporter_install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - blackbox_exporter_configure

- name: service
  ansible.builtin.import_tasks: service.yml
  become: true
  tags:
    - blackbox_exporter_run
    - blackbox_exporter_configure

...
