---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        - default.yaml
      skip: true

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    blackbox_exporter_delegate_to: "{{ ansible_host }}"
    blackbox_exporter_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/blackbox_exporter', true) }}/{{ blackbox_exporter_version }}"
  when:
    - blackbox_exporter_direct_download

- name: install dependency
  ansible.builtin.package:
    name: "{{ blackbox_exporter_requirements }}"
    state: present
  when:
    - blackbox_exporter_requirements | default([]) | count > 0

- name: get latest release
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - blackbox_exporter_version == "latest"
  block:
    - name: get latest release
      delegate_to: localhost
      become: false
      run_once: true
      bodsch.scm.github_latest:
        project: prometheus
        repository: blackbox_exporter
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      register: _latest_release

    - name: re-define blackbox_exporter_version
      ansible.builtin.set_fact:
        blackbox_exporter_version: "{{ _latest_release.latest_release }}"

- name: detect our installation path '{{ blackbox_exporter_install_path | dirname }}'
  ansible.builtin.stat:
    path: "{{ blackbox_exporter_install_path | dirname }}"
    get_checksum: false
  register: stat_blackbox_exporter_path
  ignore_errors: true

- name: old installation
  when:
    - stat_blackbox_exporter_path is defined
    - stat_blackbox_exporter_path.stat is defined
    - stat_blackbox_exporter_path.stat.isdir is defined
    - not stat_blackbox_exporter_path.stat.isdir
  block:
    - name: stop old service
      ansible.builtin.service:
        name: blackbox_exporter
        state: stopped
        enabled: false
      notify:
        - daemon-reload

    - name: remove installed systemd unit
      ansible.builtin.file:
        state: absent
        path: /etc/systemd/system/blackbox_exporter.service
      when:
        - ansible_service_mgr | lower == "systemd"

    - name: remove installed blackbox_exporter
      ansible.builtin.file:
        state: absent
        path: "{{ stat_blackbox_exporter_path.stat.path }}"

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: detect installed blackbox_exporter binary
  ansible.builtin.stat:
    path: "{{ blackbox_exporter_install_path }}/blackbox_exporter"
  register: stat_blackbox_exporter_binary

- name: create download directory
  become: false
  delegate_to: "{{ blackbox_exporter_delegate_to }}"
  ansible.builtin.file:
    path: "{{ blackbox_exporter_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: user and group handling
  when:
    - blackbox_exporter_system_user != "root"
  block:
    - name: create blackbox_exporter group
      ansible.builtin.group:
        name: "{{ blackbox_exporter_system_group }}"
        state: present
        system: true

    - name: create blackbox_exporter user
      ansible.builtin.user:
        name: "{{ blackbox_exporter_system_user }}"
        groups: "{{ blackbox_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ blackbox_exporter_install_path }}"
    state: directory
    owner: "{{ blackbox_exporter_system_user }}"
    group: "{{ blackbox_exporter_system_group }}"
    mode: 0755

- name: merge blackbox_exporter configuration between defaults and custom
  set_fact:
    blackbox_exporter_release: "{{ blackbox_exporter_defaults_release | combine(blackbox_exporter_release, recursive=True) }}"
    blackbox_exporter_service: "{{ blackbox_exporter_defaults_service | combine(blackbox_exporter_service, recursive=True) }}"

...
