---

- name: create mysql_exporter configuration directories
  ansible.builtin.file:
    path: "{{ mysql_exporter_config_dir }}"
    state: directory
    owner: root
    group: "{{ mysql_exporter_system_group }}"
    mode: 0775

- name: create mysql credentials file
  ansible.builtin.template:
    src: my.cnf.j2
    dest: "{{ mysql_exporter_service.config.my_cnf }}"
    owner: root
    group: "{{ mysql_exporter_system_group }}"
    mode: 0666
  no_log: true
  when:
    - mysql_exporter_service.config.my_cnf is defined
    - mysql_exporter_service.config.my_cnf | string | length > 0

...
