---

- name: user and group handling
  when:
    - mysql_exporter_system_user != "root"
  block:
    - name: create mysql_exporter group
      ansible.builtin.group:
        name: "{{ mysql_exporter_system_group }}"
        state: present
        system: true

    - name: create mysql_exporter user
      ansible.builtin.user:
        name: "{{ mysql_exporter_system_user }}"
        groups: "{{ mysql_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ mysql_exporter_install_path }}"
    state: directory
    owner: "{{ mysql_exporter_system_user }}"
    group: "{{ mysql_exporter_system_group }}"
    mode: 0755

- name: detect extracted binary file for mysql_exporter on '{{ mysql_exporter_delegate_to }}'
  become: false
  delegate_to: "{{ mysql_exporter_delegate_to }}"
  run_once: "{{ 'false' if mysql_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ mysql_exporter_local_tmp_directory }}/mysqld_exporter"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: detect installed mysql_exporter binary
  ansible.builtin.stat:
    path: "{{ mysql_exporter_install_path }}/{{ mysql_exporter_release.binary }}"
  register: stat_mysql_exporter_binary

- name: detect activated mysql_exporter binary
  ansible.builtin.stat:
    path: /usr/bin/{{ mysql_exporter_release.binary }}
  register: stat_mysql_exporter_activated

- name: install and activate mysql_exporter
  when:
    - stat_mysql_exporter_binary.stat is defined
    - not stat_mysql_exporter_binary.stat.exists | default('false')
    - stat_mysql_exporter_activated.stat is defined
    - not stat_mysql_exporter_activated.stat.exists | default('false')
  block:
    - name: propagate files
      block:
        - name: propagate mysql_exporter binary
          ansible.builtin.copy:
            src: "{{ mysql_exporter_local_tmp_directory }}/{{ mysql_exporter_release.binary }}"
            dest: "{{ mysql_exporter_install_path }}/{{ mysql_exporter_release.binary }}"
            mode: 0755
            owner: "{{ mysql_exporter_system_user }}"
            group: "{{ mysql_exporter_system_group }}"
            remote_src: "{{ 'true' if mysql_exporter_direct_download else 'false' }}"

        - name: make files executable
          ansible.builtin.file:
            path: "{{ mysql_exporter_install_path }}/{{ mysql_exporter_release.binary }}"
            mode: 0755
            owner: "{{ mysql_exporter_system_user }}"
            group: "{{ mysql_exporter_system_group }}"

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ mysql_exporter_install_path }}/{{ mysql_exporter_release.binary }}"
            dest: /usr/bin/{{ mysql_exporter_release.binary }}
            state: link
            force: true
            follow: false
          notify:
            - restart mysql exporter

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ mysql_exporter_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create mysql_exporter run configuration
      ansible.builtin.template:
        src: "default/mysql_exporter.j2"
        dest: "{{ mysql_exporter_defaults_directory }}/mysql_exporter"
        force: true
        owner: root
        group: "{{ mysql_exporter_system_group }}"
        mode: 0640
      notify:
        - restart mysql exporter

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/mysql_exporter.service.j2"
        dest: "{{ systemd_lib_directory }}/mysql_exporter.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart mysql exporter

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/mysql_exporter.j2"
        dest: "/etc/conf.d/mysql_exporter"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/mysql_exporter.j2"
        dest: "/etc/init.d/mysql_exporter"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  bodsch.core.facts:
    name: mysql_exporter
    facts:
      version: "{{ mysql_exporter_version }}"

...
