---

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: ensure mysql_exporter is enabled on boot
  become: true
  ansible.builtin.service:
    name: mysql_exporter
    enabled: true
    state: started

...
