---

- name: create download directory
  become: false
  delegate_to: "{{ alertmanager_delegate_to }}"
  run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ alertmanager_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: detect the downloaded alertmanager archive
  become: false
  delegate_to: "{{ alertmanager_delegate_to }}"
  run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ alertmanager_local_tmp_directory }}/alertmanager.{{ ansible_facts.system | lower }}-{{ go_arch }}.tar.gz"
  register: stat_alertmanager_archive

- name: download
  when:
    - stat_alertmanager_archive.stat is defined
    - not stat_alertmanager_archive.stat.exists | default('false')
  block:
    - name: checksum
      become: false
      delegate_to: localhost
      run_once: true
      block:
        - name: get checksum list
          bodsch.scm.github_checksum:
            project: prometheus
            repository: alertmanager
            checksum_file: sha256sums.txt
            user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
            password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
            architecture: "{{ ansible_architecture }}"
            system: "{{ ansible_facts.system }}"
            version: "v{{ alertmanager_version }}"
          register: _latest_checksum

        - name: define checksum for {{ go_arch }} architecture
          ansible.builtin.set_fact:
            __alertmanager_checksum: "sha256:{{ _latest_checksum.checksum }}"
          when:
            - _latest_checksum.rc == 0
            - _latest_checksum.checksum is defined
            - _latest_checksum.checksum | string | length > 0

    - name: download alertmanager binary archive
      become: false
      delegate_to: "{{ alertmanager_delegate_to }}"
      run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ alertmanager_release_download_url }}/download/{{ __alertmanager_files.archive }}"
        dest: "{{ alertmanager_local_tmp_directory }}/alertmanager.{{ ansible_facts.system | lower }}-{{ go_arch }}.tar.gz"
        checksum: "{{ __alertmanager_checksum | default(omit) }}"
        mode: 0660
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: extract alertmanager archive
      become: false
      delegate_to: "{{ alertmanager_delegate_to }}"
      run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
      ansible.builtin.unarchive:
        src: "{{ alertmanager_local_tmp_directory }}/alertmanager.{{ ansible_facts.system | lower }}-{{ go_arch }}.tar.gz"
        dest: "{{ alertmanager_local_tmp_directory }}"
        copy: false

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ alertmanager_delegate_to }}"
      run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ alertmanager_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.
...
