---

- name: get latest release
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - alertmanager_version == "latest"
  block:
    - name: get latest release
      delegate_to: localhost
      become: false
      run_once: true
      bodsch.scm.github_latest:
        project: prometheus
        repository: alertmanager
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      register: _latest_release

    - name: re-define alertmanager_version
      ansible.builtin.set_fact:
        alertmanager_version: "{{ _latest_release.latest_release }}"

- name: define download information
  ansible.builtin.set_fact:
    alertmanager_release: "{{ alertmanager_defaults_release | combine(alertmanager_release, recursive=True) }}"

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    alertmanager_delegate_to: "{{ ansible_host }}"
    alertmanager_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/alertmanager', true) }}/{{ alertmanager_version }}"
  when:
    - alertmanager_direct_download

- name: create download directory
  become: false
  delegate_to: "{{ alertmanager_delegate_to }}"
  run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ alertmanager_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: detect the downloaded alertmanager archive
  become: false
  delegate_to: "{{ alertmanager_delegate_to }}"
  run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ alertmanager_local_tmp_directory }}/{{ alertmanager_release.file }}"
  register: stat_alertmanager_archive

- name: download
  when:
    - stat_alertmanager_archive.stat is defined
    - not stat_alertmanager_archive.stat.exists | default('false')
  block:
    - name: checksum
      become: false
      delegate_to: localhost
      run_once: true
      block:
        - name: get checksum list
          bodsch.scm.github_checksum:
            project: prometheus
            repository: alertmanager
            checksum_file: sha256sums.txt
            user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
            password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
            architecture: "{{ ansible_architecture }}"
            system: "{{ ansible_facts.system }}"
            version: "v{{ alertmanager_version }}"
          register: _latest_checksum

        - name: define checksum for {{ system_architecture }} architecture
          ansible.builtin.set_fact:
            __alertmanager_checksum: "sha256:{{ _latest_checksum.checksum }}"
          when:
            - _latest_checksum.rc == 0
            - _latest_checksum.checksum is defined
            - _latest_checksum.checksum | string | length > 0

    - name: download alertmanager binary archive
      become: false
      delegate_to: "{{ alertmanager_delegate_to }}"
      run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ alertmanager_release.download_url }}/download/v{{ alertmanager_version }}/{{ alertmanager_release.file }}"
        dest: "{{ alertmanager_local_tmp_directory }}/{{ alertmanager_release.file }}"
        checksum: "{{ __alertmanager_checksum | default(omit) }}"
        mode: 0660
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: extract alertmanager archive
      become: false
      delegate_to: "{{ alertmanager_delegate_to }}"
      run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
      ansible.builtin.unarchive:
        src: "{{ alertmanager_local_tmp_directory }}/{{ alertmanager_release.file }}"
        dest: "{{ alertmanager_local_tmp_directory }}"
        copy: false

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ alertmanager_delegate_to }}"
      run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ alertmanager_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.

- name: detect extracted binary
  become: false
  delegate_to: "{{ alertmanager_delegate_to }}"
  run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ alertmanager_local_tmp_directory }}/{{ alertmanager_release.binary }}"
  register: stat_alertmanager_binary

- name: extract alertmanager archive
  become: false
  delegate_to: "{{ alertmanager_delegate_to }}"
  run_once: "{{ 'false' if alertmanager_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ alertmanager_local_tmp_directory }}/{{ alertmanager_release.file }}"
    dest: "{{ alertmanager_local_tmp_directory }}/"
    copy: false
    extra_opts:
      - --strip-components=1
  when:
    - stat_alertmanager_binary.stat is defined
    - not stat_alertmanager_binary.stat.exists | default('false')

...
