---

- name: detect external installation
  ansible.builtin.stat:
    path: /usr/local/bin/alertmanager
    get_checksum: false
  register: stat_alertmanager_path
  ignore_errors: true

- name: old installation
  when:
    - stat_alertmanager_path is defined
    - stat_alertmanager_path.stat is defined
    - stat_alertmanager_path.stat.isdir is defined
    - not stat_alertmanager_path.stat.isdir
  block:
    - name: stop old service
      ansible.builtin.service:
        name: alertmanager
        state: stopped
        enabled: false
      notify:
        - daemon-reload

    - name: remove installed systemd unit
      ansible.builtin.file:
        state: absent
        path: /etc/systemd/system/alertmanager.service
      when:
        - ansible_service_mgr | lower == "systemd"

    - name: remove installed alertmanager
      ansible.builtin.file:
        state: absent
        path: /usr/local/bin/alertmanager

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
