---

nginx_exporter_main_version: "{{ nginx_exporter_version[0:3] }}"

nginx_exporter_install_path: /usr/local/bin/nginx_exporter/{{ nginx_exporter_version }}

nginx_exporter_delegate_to: localhost

nginx_exporter_local_tmp_directory: "{{
  lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
  default(lookup('env', 'HOME') ~ '/.cache/ansible/nginx_exporter', true) }}/{{ nginx_exporter_version }}"

nginx_exporter_defaults_service:
  nginx:
    plus: false
    retries: 3
    retry_interval: 10s
    scrape_uri: http://127.0.0.1:8080/stub_status
    ssl_ca_cert: ""
    ssl_client_cert: ""
    ssl_client_key: ""
    ssl_verify: ""
    timeout: "10s"
  prometheus:
    const_labels: {}
  web:
    listen_address: "127.0.0.1:9113"
    secured_metrics: ""
    ssl_server_cert: ""
    ssl_server_key: ""
    telemetry_path: /metrics

nginx_exporter_defaults_directory: /etc/default

nginx_exporter_defaults_release:
  download_url: https://github.com/nginxinc/nginx-prometheus-exporter/releases
  file: nginx-prometheus-exporter_{{ nginx_exporter_version }}_{{ ansible_system | lower }}_{{ system_architecture }}.tar.gz

go_arch_map:
  i386: '386'
  x86_64: 'amd64'

system_architecture: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

systemd_lib_directory: /lib/systemd/system


...
