---

- name: converge
  hosts: instance
  any_errors_fatal: false

  pre_tasks:
    - name: d
      debug:
        msg:
          - "run_tags: {{ ansible_run_tags }}"
          - "add     : {{ ansible_run_tags | intersect(['silence_add']) | count > 0 }}"
          - "remove  : {{ ansible_run_tags | intersect(['silence_remove']) | count > 0 }}"
      tags:
        - always

  roles:
    - role: bodsch.prometheus.am_silence

- name: add silence
  hosts: instance
  any_errors_fatal: false

  roles:
    - role: bodsch.prometheus.am_silence
      when:
        - ansible_run_tags | intersect(["all","silence_add"]) | count > 0
      tags:
        - silence_add

- name: remove silence
  hosts: instance
  any_errors_fatal: false

  roles:
    - role: bodsch.prometheus.am_silence
      when:
        - ansible_run_tags | intersect(["all","silence_remove"]) | count > 0
      tags:
        - silence_remove
