---

- name: create download directory
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ pushgateway_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: detect the downloaded pushgateway archive
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ pushgateway_local_tmp_directory }}/{{ pushgateway_release.file }}"
  register: stat_pushgateway_archive

- name: download
  when:
    - stat_pushgateway_archive.stat is defined
    - not stat_pushgateway_archive.stat.exists | default('false')
  block:
    - name: checksum
      become: false
      delegate_to: localhost
      run_once: true
      block:
        - name: get checksum list
          bodsch.scm.github_checksum:
            project: prometheus
            repository: pushgateway
            checksum_file: sha256sums.txt
            user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
            password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
            architecture: "{{ ansible_architecture }}"
            system: "{{ ansible_facts.system }}"
            version: "v{{ pushgateway_version }}"
          register: _latest_checksum

        - name: define checksum for {{ system_architecture }} architecture
          ansible.builtin.set_fact:
            __pushgateway_checksum: "sha256:{{ _latest_checksum.checksum }}"
          when:
            - _latest_checksum.rc == 0
            - _latest_checksum.checksum is defined
            - _latest_checksum.checksum | string | length > 0

    - name: download pushgateway binary archive
      become: false
      delegate_to: "{{ pushgateway_delegate_to }}"
      run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ pushgateway_release.download_url }}/download/v{{ pushgateway_version }}/{{ pushgateway_release.file }}"
        dest: "{{ pushgateway_local_tmp_directory }}/{{ pushgateway_release.file }}"
        checksum: "{{ __pushgateway_checksum | default(omit) }}"
        mode: 0640
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ pushgateway_delegate_to }}"
      run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ pushgateway_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.

- name: detect extracted binary
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ pushgateway_local_tmp_directory }}/{{ pushgateway_release.binary }}"
  register: stat_pushgateway_binary

- name: extract pushgateway archive
  become: false
  delegate_to: "{{ pushgateway_delegate_to }}"
  run_once: "{{ 'false' if pushgateway_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ pushgateway_local_tmp_directory }}/{{ pushgateway_release.file }}"
    dest: "{{ pushgateway_local_tmp_directory }}/"
    copy: false
    extra_opts:
      - --strip-components=1
  when:
    - stat_pushgateway_binary.stat is defined
    - not stat_pushgateway_binary.stat.exists | default('false')

...
