---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: "ghcr.io/bodsch/docker-ansible/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    published_ports:
      - 9090:9090
    groups:
      - prometheues
    docker_networks:
      - name: prom
        ipam_config:
          - subnet: "10.18.0.0/24"
            gateway: "10.18.0.254"
    networks:
      - name: prom
        ipv4_address: "10.18.0.1"

  - name: federated
    image: "ghcr.io/bodsch/docker-ansible/ansible-${DISTRIBUTION:-debian:12}"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://run/docker.sock}"
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /var/lib/containerd
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /run
      - /tmp
    published_ports:
      - 9091:9090
    groups:
      - prometheues
    networks:
      - name: prom
        ipv4_address: "10.18.0.2"

provisioner:
  name: ansible
  ansible_args:
    - --diff
    - -v
  config_options:
    defaults:
      deprecation_warnings: true
      stdout_callback: yaml
      callbacks_enabled: profile_tasks
      gathering: smart
      fact_caching: jsonfile
      fact_caching_timeout: 8640
      fact_caching_connection: "${MOLECULE_EPHEMERAL_DIRECTORY}/ansible_facts"

scenario:
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy

verifier:
  name: testinfra
