---

- name: create node_exporter configuration directory
  ansible.builtin.file:
    path: "{{ node_exporter_config_dir }}"
    state: directory
    owner: root
    group: "{{ node_exporter_system_group }}"
    mode: 0770

- name: create node_exporter configuration
  ansible.builtin.template:
    src: "node_exporter/config.yml.j2"
    dest: "{{ node_exporter_config_dir }}/config.yml"
    force: true
    owner: root
    group: "{{ node_exporter_system_group }}"
    mode: 0640
  when:
    - node_exporter_enable_experimental
  notify:
    - restart node_exporter

...
