---

- name: user and group handling
  when:
    - not running_in_check_mode
    - node_exporter_system_user != "root"
  block:
    - name: create node_exporter group
      ansible.builtin.group:
        name: "{{ node_exporter_system_group }}"
        state: present
        system: true

    - name: create node_exporter user
      ansible.builtin.user:
        name: "{{ node_exporter_system_user }}"
        groups: "{{ node_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  when:
    - not running_in_check_mode
  ansible.builtin.file:
    path: "{{ node_exporter_install_path }}"
    state: directory
    owner: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
    mode: "0755"

- name: deploy and activate node_exporter version {{ node_exporter_version }}
  when:
    - not running_in_check_mode
  bodsch.core.deploy_and_activate:
    src_dir: "{{ node_exporter_local_tmp_directory }}"
    install_dir: "{{ node_exporter_install_path }}"
    link_dir: "/usr/bin"
    remote_src: "{{ ('true' if node_exporter_direct_download else 'false') | bool }}"
    owner: "{{ node_exporter_system_user }}"
    group: "{{ node_exporter_system_group }}"
    mode: "0755"
    items:
      - name: "{{ node_exporter_release.binary }}"
        capability: "cap_net_raw+ep"
  notify:
    - restart node exporter

- name: systemd
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "systemd"
  block:
    - name: create node_exporter run configuration
      ansible.builtin.template:
        src: "default/node_exporter.j2"
        dest: "{{ node_exporter_defaults_directory }}/node_exporter"
        force: true
        owner: root
        group: "{{ node_exporter_system_group }}"
        mode: "0640"
      notify:
        - restart node exporter

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/node_exporter.service.j2"
        dest: "{{ systemd_lib_directory }}/node_exporter.service"
        owner: root
        group: root
        mode: "0644"
      notify:
        - daemon-reload
        - restart node exporter

- name: openrc
  when:
    - not running_in_check_mode
    - ansible_facts.service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/node_exporter.j2"
        dest: "/etc/conf.d/node_exporter"
        owner: root
        group: root
        mode: "0644"

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/node_exporter.j2"
        dest: "/etc/init.d/node_exporter"
        owner: root
        group: root
        mode: "0750"

- name: create custom fact file
  when:
    - not running_in_check_mode
  bodsch.core.facts:
    name: node_exporter
    facts:
      version: "{{ node_exporter_version }}"

...
