---

- name: include OS specific configuration ({{ ansible_distribution }} ({{ ansible_os_family }}) {{ ansible_distribution_major_version }})
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yaml
      skip: true

- name: install dependency
  ansible.builtin.package:
    name: "{{ node_exporter_requirements }}"
    state: present
  when:
    - node_exporter_requirements | default([]) | count > 0

- name: merge node_exporter configuration between defaults and custom
  ansible.builtin.set_fact:
    node_exporter_service: "{{ node_exporter_defaults_service | combine(node_exporter_service, recursive=True) }}"
    node_exporter_tls_server: "{{ node_exporter_defaults_tls_server | combine(node_exporter_tls_server, recursive=True) }}"
    node_exporter_http_server: "{{ node_exporter_defaults_http_server | combine(node_exporter_http_server, recursive=True) }}"
    node_exporter_basic_auth_users: "{{ node_exporter_defaults_basic_auth_users | combine(node_exporter_basic_auth_users, recursive=True) }}"
    node_exporter_collectors: "{{ node_exporter_defaults_collectors | combine(node_exporter_collectors, recursive=True) }}"

...
