---

- name: prepare
  ansible.builtin.import_tasks: prepare.yml
  when:
    - ansible_run_tags | intersect(["silence_add","silence_remove"]) | count > 0
  tags:
    - always
    - silence_add
    - silence_remove

- name: add silence
  ansible.builtin.import_tasks: silence/add.yml
  when:
    - ansible_run_tags | intersect(["silence_add"]) | count > 0
  tags:
    - silence_add

- name: delete silence
  ansible.builtin.import_tasks: silence/remove.yml
  when:
    - ansible_run_tags | intersect(["silence_remove"]) | count > 0
  tags:
    - silence_remove

...
