---

- name: d
  debug:
    msg:
      - "run_tags: {{ ansible_run_tags }}"
      - "add     : {{ ansible_run_tags | intersect(['silence_add']) | count > 0 }}"
      - "remove  : {{ ansible_run_tags | intersect(['silence_remove']) | count > 0 }}"
  tags:
    - always


- name: prepare
  ansible.builtin.include_tasks: prepare.yml
  when:
    - ansible_run_tags | intersect(["silence_add","silence_remove"]) | count > 0
  tags:
    - always
    - silence_add
    - silence_remove

- name: add silence
  ansible.builtin.include_tasks: silence/add.yml
  when:
    - ansible_run_tags | intersect(["silence_add"]) | count > 0
  tags:
    - silence_add

- name: delete silence
  ansible.builtin.include_tasks: silence/remove.yml
  when:
    - ansible_run_tags | intersect(["silence_remove"]) | count > 0
  tags:
    - silence_remove

...
