---

- name: get latest release
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - bind_exporter_version == "latest"
  block:
    - name: get latest release
      delegate_to: localhost
      become: false
      run_once: true
      bodsch.scm.github_latest:
        project: prometheus-community
        repository: bind_exporter
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      register: _latest_release

    - name: re-define bind_exporter_version
      ansible.builtin.set_fact:
        bind_exporter_version: "{{ _latest_release.latest_release }}"

- name: define download information
  ansible.builtin.set_fact:
    bind_exporter_release: "{{ bind_exporter_defaults_release | combine(bind_exporter_release, recursive=True) }}"

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    bind_exporter_delegate_to: "{{ ansible_host }}"
    bind_exporter_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/bind_exporter', true) }}/{{ bind_exporter_version }}"
  when:
    - bind_exporter_direct_download

- name: create download directory
  become: false
  delegate_to: "{{ bind_exporter_delegate_to }}"
  run_once: "{{ 'false' if bind_exporter_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ bind_exporter_local_tmp_directory }}"
    state: directory
    mode: "0750"
  check_mode: false

- name: detect the downloaded bind_exporter archive
  become: false
  delegate_to: "{{ bind_exporter_delegate_to }}"
  run_once: "{{ 'false' if bind_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ bind_exporter_local_tmp_directory }}/{{ bind_exporter_release.file }}"
  register: stat_bind_exporter_archive

- name: download
  when:
    - stat_bind_exporter_archive.stat is defined
    - not stat_bind_exporter_archive.stat.exists | default('false')
    - not running_in_check_mode
  block:
    - name: checksum
      become: false
      delegate_to: localhost
      run_once: true
      block:
        - name: get checksum list
          bodsch.scm.github_checksum:
            project: prometheus-community
            repository: bind_exporter
            checksum_file: sha256sums.txt
            user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
            password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
            architecture: "{{ ansible_architecture }}"
            system: "{{ ansible_facts.system }}"
            version: "v{{ bind_exporter_version }}"
          register: _latest_checksum

        - name: define checksum for {{ system_architecture }} architecture
          ansible.builtin.set_fact:
            __bind_exporter_checksum: "sha256:{{ _latest_checksum.checksum }}"
          when:
            - _latest_checksum is defined
            - _latest_checksum.rc is defined
            - _latest_checksum.rc == 0
            - _latest_checksum.checksum is defined
            - _latest_checksum.checksum | string | length > 0

    - name: download bind_exporter binary archive
      become: false
      delegate_to: "{{ bind_exporter_delegate_to }}"
      run_once: "{{ 'false' if bind_exporter_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ bind_exporter_release.download_url }}/download/v{{ bind_exporter_version }}/{{ bind_exporter_release.file }}"
        dest: "{{ bind_exporter_local_tmp_directory }}/{{ bind_exporter_release.file }}"
        checksum: "{{ __bind_exporter_checksum | default(omit) }}"
        mode: "0640"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ bind_exporter_delegate_to }}"
      run_once: "{{ 'false' if bind_exporter_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ bind_exporter_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.

- name: detect extracted binary
  become: false
  delegate_to: "{{ bind_exporter_delegate_to }}"
  run_once: "{{ 'false' if bind_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ bind_exporter_local_tmp_directory }}/{{ bind_exporter_release.binary }}"
  register: stat_bind_exporter_binary

- name: extract bind_exporter archive
  become: false
  delegate_to: "{{ bind_exporter_delegate_to }}"
  run_once: "{{ 'false' if bind_exporter_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ bind_exporter_local_tmp_directory }}/{{ bind_exporter_release.file }}"
    dest: "{{ bind_exporter_local_tmp_directory }}/"
    copy: false
    extra_opts:
      - --strip-components=1
  when:
    - not running_in_check_mode
    - stat_bind_exporter_binary.stat is defined
    - not stat_bind_exporter_binary.stat.exists | default('false')

...
