---

- name: user and group handling
  when:
    - bind_exporter_system_user != "root"
  block:
    - name: create bind_exporter group
      ansible.builtin.group:
        name: "{{ bind_exporter_system_group }}"
        state: present
        system: true

    - name: create bind_exporter user
      ansible.builtin.user:
        name: "{{ bind_exporter_system_user }}"
        groups: "{{ bind_exporter_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ bind_exporter_install_path }}"
    state: directory
    owner: "{{ bind_exporter_system_user }}"
    group: "{{ bind_exporter_system_group }}"
    mode: 0755

- name: detect extracted binary file for bind_exporter on '{{ bind_exporter_delegate_to }}'
  become: false
  delegate_to: "{{ bind_exporter_delegate_to }}"
  run_once: "{{ 'false' if bind_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ bind_exporter_local_tmp_directory }}/{{ bind_exporter_release.binary }}"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not running_in_check_mode
    - not stat_file_binary.stat.exists

- name: detect installed bind_exporter binary
  ansible.builtin.stat:
    path: "{{ bind_exporter_install_path }}/{{ bind_exporter_release.binary }}"
  register: stat_bind_exporter_binary

- name: detect activated bind_exporter binary
  ansible.builtin.stat:
    path: /usr/bin/{{ bind_exporter_release.binary }}
  register: stat_bind_exporter_activated

- name: install and activate bind_exporter
  when:
    - not running_in_check_mode
    - stat_file_binary.stat.exists
    - (stat_bind_exporter_binary.stat is defined and not stat_bind_exporter_binary.stat.exists | default('false')) or
      not stat_bind_exporter_activated.stat | bodsch.prometheus.linked_version(bind_exporter_install_path, bind_exporter_version)
  block:
    - name: propagate files
      block:
        - name: propagate bind_exporter binary
          ansible.builtin.copy:
            src: "{{ bind_exporter_local_tmp_directory }}/{{ bind_exporter_release.binary }}"
            dest: "{{ bind_exporter_install_path }}/{{ bind_exporter_release.binary }}"
            mode: 0755
            owner: "{{ bind_exporter_system_user }}"
            group: "{{ bind_exporter_system_group }}"
            remote_src: "{{ 'true' if bind_exporter_direct_download else 'false' }}"

        - name: make files executable
          ansible.builtin.file:
            path: "{{ bind_exporter_install_path }}/{{ bind_exporter_release.binary }}"
            mode: 0755
            owner: "{{ bind_exporter_system_user }}"
            group: "{{ bind_exporter_system_group }}"

        - name: ensure bind exporter binary has cap_net_raw capability
          capabilities:
            path: "{{ bind_exporter_install_path }}/{{ bind_exporter_release.binary }}"
            capability: cap_net_raw+ep
            state: present

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ bind_exporter_install_path }}/{{ bind_exporter_release.binary }}"
            dest: /usr/bin/{{ bind_exporter_release.binary }}
            state: link
            force: true
            follow: false
          notify:
            - restart bind exporter

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ bind_exporter_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
    - not running_in_check_mode
  block:
    - name: create bind_exporter run configuration
      ansible.builtin.template:
        src: "default/bind_exporter.j2"
        dest: "{{ bind_exporter_defaults_directory }}/bind_exporter"
        force: true
        owner: root
        group: "{{ bind_exporter_system_group }}"
        mode: 0640
      notify:
        - restart bind exporter

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/bind_exporter.service.j2"
        dest: "{{ systemd_lib_directory }}/bind_exporter.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart bind exporter

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
    - not running_in_check_mode
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/bind_exporter.j2"
        dest: "/etc/conf.d/bind_exporter"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/bind_exporter.j2"
        dest: "/etc/init.d/bind_exporter"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  when:
    - not running_in_check_mode
  bodsch.core.facts:
    name: bind_exporter
    facts:
      version: "{{ bind_exporter_version }}"

...
