---

# - name: warn against the use of obsolete variables
#   when:
#     - bind_exporter_config | default([]) | count > 0
#   block:
#     - name: warn against the use of obsolete variables  # noqa ignore-errors
#       ansible.builtin.fail:
#         msg: |
#           The use of `bind_exporter_config` is obsolete!
#           Please use `bind_exporter_modules` instead!
#           The obsolete variable is automatically converted internally.
#           The conversion will be removed in one of the next releases!
#       ignore_errors: true
#
#     # - name: wait 5 seconds to realise the message
#     #   delegate_to: localhost
#     #   ansible.builtin.wait_for:
#     #     timeout: 10
#
#     - name: convert obsolete variable ...
#       ansible.builtin.set_fact:
#         bind_exporter_modules: "{{ bind_exporter_config | bodsch.prometheus.convert_to_modules(bind_exporter_modules) }}"
#         bind_exporter_config: []

- name: prepare
  ansible.builtin.import_tasks: prepare.yml
  tags:
    - bind_exporter_install
    - bind_exporter_configure
    - bind_exporter_run

- name: download archive
  ansible.builtin.import_tasks: download.yml
  tags:
    - bind_exporter_install

- name: external installation
  ansible.builtin.import_tasks: external_installation.yml
  tags:
    - bind_exporter_install

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - bind_exporter_install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - bind_exporter_configure

- name: service
  ansible.builtin.import_tasks: service.yml
  tags:
    - bind_exporter_run
    - bind_exporter_configure

...
