---

- name: converge
  hosts: instance
  any_errors_fatal: false

  roles:
    - role: bodsch.prometheus.silence


- name: add silence
  hosts: instance
  any_errors_fatal: false

  pre_tasks:
    - name: d
      debug:
        msg:
          - "{{ ansible_run_tags }}"
          - "{{ ansible_run_tags | intersect(['all','silence_add']) | count > 0 }}"
      tags:
        - always

  roles:
    - role: bodsch.prometheus.silence
      when:
        - ansible_run_tags | intersect(["all","silence_add"]) | count > 0
      tags:
        - silence_add
