---

node_exporter_system_user: node_exporter
node_exporter_system_group: node_exporter
node_exporter_config_dir: /etc/node_exporter
node_exporter_textfile_dir: /var/lib/node_exporter

node_exporter_collector_scripts: []
  # - name: apt
  #   cron:
  #     enabled: true
  #     minute: "10"
  #     hour: "*/1"
  #     job: "{{ node_exporter_install_path }}/collector-scripts/apt.sh > {{ node_exporter_textfile_dir }}/apt.prom"
  # - name: required-reboot
  #   cron:
  #     enabled: false
  #     minute: 0
  #     hour: "*/1"
  #     job: "{{ node_exporter_install_path }}/collector-scripts/required-reboot.sh > {{ node_exporter_textfile_dir }}/required-reboot.prom"

node_exporter_external_repository:
  enabled: true
  url: https://github.com/prometheus-community/node-exporter-textfile-collector-scripts.git
  version: master
...
