---

- name: daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  notify: restart alertmanager
  when:
    - ansible_service_mgr == 'systemd'

- name: validate config
  bodsch.prometheus.amtool:
    verbose: false
    state: check
    config: "{{ alertmanager_config_dir }}/alertmanager.yml"
  register: alertmanger_valid_config
  when:
    - not running_in_check_mode
    - alertmanger_config is defined
    - alertmanger_config.changed is defined
    - alertmanger_config.changed
  notify:
    - restart alertmanager

- name: reload alertmanager
  become: true
  ansible.builtin.service:
    name: alertmanager
    state: reloaded
  when:
    - not running_in_check_mode

- name: restart alertmanager
  become: true
  ansible.builtin.service:
    name: alertmanager
    state: restarted
  when:
    - not running_in_check_mode
    - alertmanger_valid_config is defined
    - alertmanger_valid_config.rc is defined
    - alertmanger_valid_config.rc == 0

...
