---

prometheus_service:
  log:
    level: debug
  web:
    listen_address: "0.0.0.0:9190"
    enable_lifecycle: true
    enable_remote_write_receiver: true
    enable_admin_api: true
  features:
    - remote-write-receiver

prometheus_global:
  scrape_interval: 5m
  evaluation_interval: 2m

prometheus_scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - "localhost:9190"

prometheus_remote_read:
  - url: 'https://10.18.0.2:9190/api/v1/read'
    basic_auth:
      username: 'your-username'
      password: 'your-password'

...
