---

node_exporter_system_user: node_exporter
node_exporter_system_group: node_exporter
node_exporter_config_dir: /etc/node_exporter
node_exporter_textfile_dir: /var/lib/node_exporter

node_exporter_collector_scripts:
  - apt.sh
  # - solr_response.sh

node_exporter_solr_response:
  url: "" # https://admin.cmsqa.arri.com/admin
  core: live
  instance: solr-master
  endpoints:
    - dvinci
    - eventbrite

...
