---

- name: get latest release
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - prometheus_version == "latest"
  block:
    - name: get latest release
      delegate_to: localhost
      become: false
      run_once: true
      bodsch.scm.github_latest:
        project: prometheus
        repository: prometheus
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      register: _latest_release

    - name: re-define prometheus_version
      ansible.builtin.set_fact:
        prometheus_version: "{{ _latest_release.latest_release }}"

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    prometheus_delegate_to: "{{ ansible_host }}"
    prometheus_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/prometheus', true) }}/{{ prometheus_version }}"
  when:
    - prometheus_direct_download

- name: create download directory
  become: false
  delegate_to: "{{ prometheus_delegate_to }}"
  run_once: "{{ 'false' if prometheus_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ prometheus_local_tmp_directory }}"
    state: directory
    mode: 0750

- name: detect the downloaded prometheus archive
  become: false
  delegate_to: "{{ prometheus_delegate_to }}"
  run_once: "{{ 'false' if prometheus_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ prometheus_local_tmp_directory }}/{{ prometheus_release.file }}"
  register: stat_prometheus_archive

- name: download
  when:
    - stat_prometheus_archive.stat is defined
    - not stat_prometheus_archive.stat.exists | default('false')
  block:
    - name: checksum
      become: false
      delegate_to: localhost
      run_once: true
      block:
        - name: get checksum list
          bodsch.scm.github_checksum:
            project: prometheus
            repository: prometheus
            checksum_file: sha256sums.txt
            user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
            password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
            architecture: "{{ ansible_architecture }}"
            system: "{{ ansible_facts.system }}"
            version: "v{{ prometheus_version }}"
          register: _latest_checksum

        - name: define checksum for {{ system_architecture }} architecture
          ansible.builtin.set_fact:
            __prometheus_checksum: "sha256:{{ _latest_checksum.checksum }}"
          when:
            - _latest_checksum.rc == 0
            - _latest_checksum.checksum is defined
            - _latest_checksum.checksum | string | length > 0

    - name: download prometheus binary archive
      become: false
      delegate_to: "{{ prometheus_delegate_to }}"
      run_once: "{{ 'false' if prometheus_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ prometheus_release.download_url }}/download/v{{ prometheus_version }}/{{ prometheus_release.file }}"
        dest: "{{ prometheus_local_tmp_directory }}/{{ prometheus_release.file }}"
        checksum: "{{ __prometheus_checksum | default(omit) }}"
        mode: 0640
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ prometheus_delegate_to }}"
      run_once: "{{ 'false' if prometheus_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ prometheus_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.

- name: detect extracted binary
  become: false
  delegate_to: "{{ prometheus_delegate_to }}"
  run_once: "{{ 'false' if prometheus_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ prometheus_local_tmp_directory }}/{{ prometheus_release.binary }}"
  register: stat_prometheus_binary

- name: extract prometheus archive
  become: false
  delegate_to: "{{ prometheus_delegate_to }}"
  run_once: "{{ 'false' if prometheus_direct_download else 'true' }}"
  ansible.builtin.unarchive:
    src: "{{ prometheus_local_tmp_directory }}/{{ prometheus_release.file }}"
    dest: "{{ prometheus_local_tmp_directory }}/"
    copy: false
    extra_opts:
      - --strip-components=1
  when:
    - stat_prometheus_binary.stat is defined
    - not stat_prometheus_binary.stat.exists | default('false')

...
