---

- name: user and group handling
  when:
    - prometheus_system_user != "root"
  block:
    - name: create prometheus group
      ansible.builtin.group:
        name: "{{ prometheus_system_group }}"
        state: present
        system: true

    - name: create prometheus user
      ansible.builtin.user:
        name: "{{ prometheus_system_user }}"
        groups: "{{ prometheus_system_group }}"
        append: true
        shell: /usr/sbin/nologin
        system: true
        createhome: false
        home: /nonexistent

- name: create install directory
  ansible.builtin.file:
    path: "{{ prometheus_install_path }}"
    state: directory
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0755

- name: detect extracted binary file for prometheus on '{{ prometheus_delegate_to }}'
  become: false
  delegate_to: "{{ prometheus_delegate_to }}"
  run_once: "{{ 'false' if prometheus_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ prometheus_local_tmp_directory }}/{{ prometheus_release.binary }}"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: detect installed prometheus binary
  ansible.builtin.stat:
    path: "{{ prometheus_install_path }}/{{ prometheus_release.binary }}"
  register: stat_prometheus_binary

- name: detect activated prometheus binary
  ansible.builtin.stat:
    path: /usr/bin/prometheus
  register: stat_prometheus_activated

- name: install and activate prometheus
  when:
    - (stat_prometheus_binary.stat is defined and not stat_prometheus_binary.stat.exists | default('false')) or
      not stat_prometheus_activated.stat | bodsch.prometheus.linked_version(prometheus_install_path, prometheus_version)
    block:
    - name: propagate files
      block:
        - name: propagate prometheus binaries
          ansible.builtin.copy:
            src: "{{ prometheus_local_tmp_directory }}/{{ item }}"
            dest: "{{ prometheus_install_path }}/{{ item }}"
            mode: 0755
            owner: "{{ prometheus_system_user }}"
            group: "{{ prometheus_system_group }}"
            remote_src: "{{ 'true' if prometheus_direct_download else 'false' }}"
          loop:
            - "{{ prometheus_release.binary }}"
            - promtool

        - name: make files executable
          ansible.builtin.file:
            path: "{{ prometheus_install_path }}/{{ item }}"
            mode: 0755
            owner: "{{ prometheus_system_user }}"
            group: "{{ prometheus_system_group }}"
          loop:
            - "{{ prometheus_release.binary }}"
            - promtool

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ prometheus_install_path }}/{{ item }}"
            dest: "/usr/bin/{{ item }}"
            state: link
            force: true
            follow: false
          loop:
            - "{{ prometheus_release.binary }}"
            - promtool
          notify:
            - restart prometheus

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ prometheus_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: create prometheus data directory
  ansible.builtin.file:
    path: "{{ prometheus_data_dir }}"
    state: directory
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0755

- name: create prometheus configuration directory
  ansible.builtin.file:
    path: "{{ prometheus_config_dir }}"
    state: directory
    owner: root
    group: "{{ prometheus_system_group }}"
    mode: 0770

- name: create rules directory
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_config_dir }}/rules"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0750

- name: create targets directory
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_config_dir }}/targets"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0750

- name: create file_sd directory
  ansible.builtin.file:
    state: directory
    path: "{{ prometheus_config_dir }}/file_sd"
    owner: "{{ prometheus_system_user }}"
    group: "{{ prometheus_system_group }}"
    mode: 0750

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create prometheus run configuration
      ansible.builtin.template:
        src: "default/prometheus.j2"
        dest: "{{ prometheus_defaults_directory }}/prometheus"
        force: true
        owner: root
        group: "{{ prometheus_system_group }}"
        mode: 0640
      notify:
        - reload prometheus

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/prometheus.service.j2"
        dest: "{{ systemd_lib_directory }}/prometheus.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/prometheus.j2"
        dest: "/etc/conf.d/prometheus"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/prometheus.j2"
        dest: "/etc/init.d/prometheus"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  bodsch.core.facts:
    name: prometheus
    facts:
      version: "{{ prometheus_version }}"

...
