---

- name: validate config
  bodsch.prometheus.promtool:
    state: check
    config: "{{ prometheus_config_dir }}/prometheus.yml"

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: ensure prometheus is enabled on boot
  become: true
  ansible.builtin.service:
    name: prometheus
    enabled: true
    state: started

...
