---

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/nginx_exporter.service.j2"
        dest: "{{ systemd_lib_directory }}/nginx_exporter.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart nginx_exporter

- name: create nginx_exporter configuration directory
  ansible.builtin.file:
    path: "{{ nginx_exporter_config_dir }}"
    state: directory
    owner: root
    group: "{{ nginx_exporter_system_group }}"
    mode: 0770

- name: create nginx_exporter run configuration
  ansible.builtin.template:
    src: "default/nginx_exporter.j2"
    dest: "{{ nginx_exporter_defaults_directory }}/nginx_exporter"
    force: true
    owner: root
    group: "{{ nginx_exporter_system_group }}"
    mode: 0644
  notify:
    - restart nginx_exporter

- name: flush handlers
  ansible.builtin.meta: flush_handlers

...
