---

- name: flush handlers
  ansible.builtin.meta: flush_handlers

- name: ensure nginx_exporter is enabled on boot
  become: true
  ansible.builtin.service:
    name: nginx_exporter
    enabled: true
    state: started

...

