---

- name: create install directory
  ansible.builtin.file:
    path: "{{ json_exporter_install_path }}"
    state: directory
    owner: "{{ json_exporter_system_user }}"
    group: "{{ json_exporter_system_group }}"
    mode: 0755

- name: detect extracted binary file for json_exporter on '{{ json_exporter_delegate_to }}'
  become: false
  delegate_to: "{{ json_exporter_delegate_to }}"
  run_once: "{{ 'false' if json_exporter_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ json_exporter_local_tmp_directory }}/{{ json_exporter_release.binary }}"
  register: stat_file_binary

- name: fail when extracted binary are missing
  ansible.builtin.fail:
    msg: "missing extracted binary on ansible controller"
  when:
    - not stat_file_binary.stat.exists

- name: detect installed json_exporter binary
  ansible.builtin.stat:
    path: "{{ json_exporter_install_path }}/{{ json_exporter_release.binary }}"
  register: stat_json_exporter_binary

- name: detect activated json_exporter binary
  ansible.builtin.stat:
    path: /usr/bin/{{ json_exporter_release.binary }}
  register: stat_json_exporter_activated

- name: install and activate json_exporter
  when:
    - stat_json_exporter_binary.stat is defined
    - not stat_json_exporter_binary.stat.exists | default('false')
    - stat_json_exporter_activated.stat is defined
    - not stat_json_exporter_activated.stat.exists | default('false')
  block:
    - name: propagate files
      block:
        - name: propagate json_exporter binary
          ansible.builtin.copy:
            src: "{{ json_exporter_local_tmp_directory }}/{{ json_exporter_release.binary }}"
            dest: "{{ json_exporter_install_path }}/{{ json_exporter_release.binary }}"
            mode: 0755
            owner: "{{ json_exporter_system_user }}"
            group: "{{ json_exporter_system_group }}"
            remote_src: "{{ 'true' if json_exporter_direct_download else 'false' }}"

        - name: make files executable
          ansible.builtin.file:
            path: "{{ json_exporter_install_path }}/{{ json_exporter_release.binary }}"
            mode: 0755
            owner: "{{ json_exporter_system_user }}"
            group: "{{ json_exporter_system_group }}"

        - name: ensure json exporter binary has cap_net_raw capability
          capabilities:
            path: "{{ json_exporter_install_path }}/{{ json_exporter_release.binary }}"
            capability: cap_net_raw+ep
            state: present
          when:
            - not ansible_check_mode

        - name: create link to binary
          ansible.builtin.file:
            src: "{{ json_exporter_install_path }}/{{ json_exporter_release.binary }}"
            dest: /usr/bin/{{ json_exporter_release.binary }}
            state: link
            force: true
            follow: false
          notify:
            - restart json exporter

      rescue:
        - name: delete install directory
          ansible.builtin.file:
            path: "{{ json_exporter_install_path }}"
            state: absent

        - name: exit with fail
          ansible.builtin.fail:
            msg: A serious error occurred during the installation of the binary.

- name: systemd
  when:
    - ansible_service_mgr | lower == "systemd"
  block:
    - name: create json_exporter run configuration
      ansible.builtin.template:
        src: "default/json_exporter.j2"
        dest: "{{ json_exporter_defaults_directory }}/json_exporter"
        force: true
        owner: root
        group: "{{ json_exporter_system_group }}"
        mode: 0640
      notify:
        - restart json exporter

    - name: create systemd service unit
      ansible.builtin.template:
        src: "init/systemd/json_exporter.service.j2"
        dest: "{{ systemd_lib_directory }}/json_exporter.service"
        owner: root
        group: root
        mode: 0644
      notify:
        - daemon-reload
        - restart json exporter

- name: openrc
  when:
    - ansible_service_mgr | lower == "openrc"
  block:
    - name: create openrc service configuration
      ansible.builtin.template:
        src: "init/openrc/conf.d/json_exporter.j2"
        dest: "/etc/conf.d/json_exporter"
        owner: root
        group: root
        mode: 0644

    - name: create openrc init configuration
      ansible.builtin.template:
        src: "init/openrc/init.d/json_exporter.j2"
        dest: "/etc/init.d/json_exporter"
        owner: root
        group: root
        mode: 0750

- name: create custom fact file
  bodsch.core.facts:
    name: json_exporter
    facts:
      version: "{{ json_exporter_version }}"

...
