---

- name: add silence
  ansible.builtin.include_tasks: silence/add.yml
  #when:
  #  - inventory_name is defined
  #  - inventory_name | length != 0
  #  # - alertmanager_add_silence | default(false)
  tags:
    - silence_add

- name: delete silence
  ansible.builtin.include_tasks: silence/remove.yml
  when:
    - inventory_name is defined
    - inventory_name | length != 0
    - alertmanager_delete_silence | default(false)
  tags:
    - delete_alertmanager_silence

...
