---

galaxy_info:
  role_name: promcheck
  namespace: bodsch

  author: Bodo Schulz
  description: ansible role to setup promcheck

  license: Apache
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 10
        - buster
        # 11
        - bullseye
    - name: Ubuntu
      versions:
        # 20.04
        - focal
    - name: EL
      versions:
        - "8"

  galaxy_tags:
    - collector
    - monitoring
    - metrics
    - system
    - prometheus

dependencies: []

...
