---

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

- name: reload docker-sd
  become: true
  ansible.builtin.service:
    name: docker-sd
    state: reloaded
  when:
    - not running_in_check_mode

- name: restart docker-sd
  become: true
  ansible.builtin.service:
    name: docker-sd
    state: restarted
  when:
    - not running_in_check_mode

...
