---

galaxy_info:
  role_name: node_exporter_textfile_collectors
  namespace: bodsch

  author: Bodo Schulz
  description: add some helper scripts for node_exporter

  license: Apache
  min_ansible_version: "2.9"

  platforms:
    - name: ArchLinux
    - name: Debian
      versions:
        # 10
        - buster
        # 11
        - bullseye
    - name: Ubuntu
      versions:
        # 20.04
        - focal

  galaxy_tags:
    - collector
    - monitoring
    - metrics
    - system
    - prometheus

dependencies: []

...
