 ---
name: role prometheus

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
  push:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'roles/prometheus/**'
      - '.github/workflows/test_role_prometheus.yml'
      - '.config/ansible-lint.yml'
      - '.yamllint'
  pull_request:
    branches:
      - 'feature/**'
      - 'fix/**'
      - '!doc/**'
    paths:
      - 'roles/prometheus/**'
      - '.github/workflows/test_role_prometheus.yml'
      - '.config/ansible-lint.yml'
      - '.yamllint'

env:
  COLLECTION_NAMESPACE: bodsch
  COLLECTION_NAME: prometheus

defaults:
  run:
    working-directory: 'ansible-collection-prometheus'

jobs:
  deb:
    name: "${{ matrix.image }} / ansible: ${{ matrix.ansible-version }} / python: ${{ matrix.python_version }}"
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'schedule' || github.event.workflow_run.conclusion == 'success' }}
    strategy:
      fail-fast: false
      matrix:
        image:
          - debian:11
        ansible-version:
          - '6.7'
        python_version:
          - 3.6
          - 3.7
          - 3.8
          - 3.10
        scenario:
          - default
          - configured
          - latest
          - upgrade
          - federation
        collection_role:
          - prometheus

    steps:
      - name: check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'ansible-collection-core'

      - name: 🐍 set up python
        uses: actions/setup-python@v4
        with:
          python-version: "${{ matrix.python_version }}"

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt

      - name: Install collection
        run: |
          make \
            install
          # mkdir -p ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE
          # cp -a ../ansible-collection-$COLLECTION_NAME ~/.ansible/collections/ansible_collections/$COLLECTION_NAMESPACE/$COLLECTION_NAME

      - name: test with tox
        run: |
          make \
            test \
              -e TOX_SCENARIO="${{ matrix.scenario }}" \
              -e TOX_ANSIBLE="ansible_${{ matrix.ansible-version }}" \
              -e DISTRIBUTION="${{ matrix.image }}" \
              -e COLLECTION_ROLE="${{ matrix.collection_role }}"
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DISTRIBUTION: ${{ matrix.image }}
          COLLECTION_ROLE: ${{ matrix.collection_role }}
          TOX_SCENARIO: ${{ matrix.scenario }}
          TOX_ANSIBLE: ansible_${{ matrix.ansible-version }}
